### ISSUE TITLE
is_support not supported?

### ISSUE THREAD

**Issue by patrickkwang** [cbizon/protocop#40]
```
File "[...]/protocop/builder/chemotext.py", line 106, in term_to_term
    ke= KEdge( 'chemotext', 'term_to_term', { 'publications': articles }, is_support = True )
TypeError: __init__() got an unexpected keyword argument 'is_support'
```
I suspect that this is actually an unpushed upgrade to reasoner, but given that reasoner independently is not broken, this seemed like the more appropriate place to submit an issue.

**Comment by cbizon** [comment]
Sorry about that.  I've pushed the change to reasoner.
